import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage();
const msgs = [];
p.on('console', m => msgs.push('['+m.type()+'] '+m.text().slice(0,300)));
p.on('pageerror', e => msgs.push('[pageerror] '+e.message.slice(0,300)));
await p.goto('http://localhost:4173/about', { waitUntil:'networkidle' });
await p.waitForTimeout(2500);
console.log('=== console output on /about (prerendered + hydrate) ===');
msgs.forEach(m=>console.log('  '+m));
if(!msgs.length) console.log('  (none)');
await b.close();
